"""Локалізовані тексти інтерфейсу (uk / ru / en)."""

LANGS = {
    "uk": "🇺🇦 Українська",
    "ru": "🇷🇺 Русский",
    "en": "🇬🇧 English",
}

CHOOSE_LANG = (
    "🌐 Оберіть мову перекладу / Выберите язык перевода / Choose translation language:"
)

T = {
    "uk": {
        "lang_set": "✅ Мову перекладу змінено.",
        "menu_hint": "Я допоможу вивчати слова. Зараз вивчаємо: {learn}. Користуйтеся меню знизу 👇",
        "btn_add": "➕ Додати слово",
        "btn_words": "📚 Мої слова",
        "btn_ai": "🤖 AI-пояснення",
        "btn_interval": "⏰ Інтервал",
        "btn_lang": "🌐 Мова",
        "btn_learn": "🎓 Що вчимо",
        "learn_title": "🎓 Яку мову хочете вивчати?\nПоточна: {current}",
        "learn_en": "🇬🇧 Англійська",
        "learn_it": "🇮🇹 Італійська",
        "learn_set": "✅ Тепер вивчаємо: {label}",
        "add_word_prompt": "✍️ Введіть слово або вираз, яке вивчаєте.\n/cancel — скасувати",
        "add_tr_prompt": "Тепер введіть переклад для «{word}»:",
        "word_saved": "✅ Збережено: {word} — {tr}",
        "word_invalid": "⚠️ Текст має бути від 1 до 100 символів. Спробуйте ще раз.",
        "words_limit": "⚠️ Досягнуто ліміт власних слів ({n}).",
        "cancelled": "Скасовано.",
        "cat_title": "📚 Оберіть категорію для вивчення.\nЦя ж категорія використовується для нагадувань.",
        "cat_all": "Усі слова",
        "cat_greetings": "Привітання",
        "cat_polite": "Ввічливість",
        "cat_basic": "Базові слова",
        "cat_food": "Їжа",
        "cat_custom": "Мої слова",
        "words_header": "📖 {cat} ({n}):",
        "words_empty": "У цій категорії поки немає слів.",
        "ai_prompt": "🤖 Введіть слово або вираз — поясню його значення в реальному житті.\nЗалишилось запитів цього тижня: {left}/{limit}\n/cancel — скасувати",
        "ai_wait": "⏳ Думаю…",
        "ai_limit": "🚫 Ліміт AI-запитів вичерпано ({limit} на тиждень).\nОновиться: {when}.",
        "ai_footer": "Залишилось AI-запитів: {left}/{limit}",
        "ai_error": "😕 Не вдалося отримати відповідь від AI. Запит не списано — спробуйте пізніше.",
        "int_title": "⏰ Як часто надсилати слова для повторення?\nПоточне: {current}",
        "i_60": "Щогодини",
        "i_120": "Кожні 2 години",
        "i_240": "Кожні 4 години",
        "i_1440": "Раз на день",
        "i_twice": "Зранку і ввечері (9:00 / 20:00)",
        "i_off": "Вимкнути",
        "int_set": "✅ Інтервал сповіщень: {label}",
        "notif_footer": "Натисніть на приховане, щоб побачити переклад",
        "hint": "Користуйтеся меню знизу 👇",
    },
    "ru": {
        "lang_set": "✅ Язык перевода изменён.",
        "menu_hint": "Я помогу учить слова. Сейчас учим: {learn}. Пользуйтесь меню внизу 👇",
        "btn_add": "➕ Добавить слово",
        "btn_words": "📚 Мои слова",
        "btn_ai": "🤖 AI-объяснение",
        "btn_interval": "⏰ Интервал",
        "btn_lang": "🌐 Язык",
        "btn_learn": "🎓 Что учим",
        "learn_title": "🎓 Какой язык хотите изучать?\nТекущий: {current}",
        "learn_en": "🇬🇧 Английский",
        "learn_it": "🇮🇹 Итальянский",
        "learn_set": "✅ Теперь учим: {label}",
        "add_word_prompt": "✍️ Введите слово или выражение, которое изучаете.\n/cancel — отмена",
        "add_tr_prompt": "Теперь введите перевод для «{word}»:",
        "word_saved": "✅ Сохранено: {word} — {tr}",
        "word_invalid": "⚠️ Текст должен быть от 1 до 100 символов. Попробуйте ещё раз.",
        "words_limit": "⚠️ Достигнут лимит собственных слов ({n}).",
        "cancelled": "Отменено.",
        "cat_title": "📚 Выберите категорию для изучения.\nЭта же категория используется для напоминаний.",
        "cat_all": "Все слова",
        "cat_greetings": "Приветствия",
        "cat_polite": "Вежливость",
        "cat_basic": "Базовые слова",
        "cat_food": "Еда",
        "cat_custom": "Мои слова",
        "words_header": "📖 {cat} ({n}):",
        "words_empty": "В этой категории пока нет слов.",
        "ai_prompt": "🤖 Введите слово или выражение — объясню его значение в реальной жизни.\nОсталось запросов на этой неделе: {left}/{limit}\n/cancel — отмена",
        "ai_wait": "⏳ Думаю…",
        "ai_limit": "🚫 Лимит AI-запросов исчерпан ({limit} в неделю).\nОбновится: {when}.",
        "ai_footer": "Осталось AI-запросов: {left}/{limit}",
        "ai_error": "😕 Не удалось получить ответ от AI. Запрос не списан — попробуйте позже.",
        "int_title": "⏰ Как часто присылать слова для повторения?\nТекущее: {current}",
        "i_60": "Каждый час",
        "i_120": "Каждые 2 часа",
        "i_240": "Каждые 4 часа",
        "i_1440": "Раз в день",
        "i_twice": "Утром и вечером (9:00 / 20:00)",
        "i_off": "Выключить",
        "int_set": "✅ Интервал уведомлений: {label}",
        "notif_footer": "Нажмите на скрытый текст, чтобы увидеть перевод",
        "hint": "Пользуйтесь меню внизу 👇",
    },
    "en": {
        "lang_set": "✅ Translation language updated.",
        "menu_hint": "I'll help you learn words. Currently learning: {learn}. Use the menu below 👇",
        "btn_add": "➕ Add word",
        "btn_words": "📚 My words",
        "btn_ai": "🤖 AI explanation",
        "btn_interval": "⏰ Interval",
        "btn_lang": "🌐 Language",
        "btn_learn": "🎓 What to learn",
        "learn_title": "🎓 Which language do you want to learn?\nCurrent: {current}",
        "learn_en": "🇬🇧 English",
        "learn_it": "🇮🇹 Italian",
        "learn_set": "✅ Now learning: {label}",
        "add_word_prompt": "✍️ Enter the word or expression you are learning.\n/cancel to abort",
        "add_tr_prompt": "Now enter the translation for “{word}”:",
        "word_saved": "✅ Saved: {word} — {tr}",
        "word_invalid": "⚠️ Text must be 1–100 characters long. Try again.",
        "words_limit": "⚠️ You have reached the custom words limit ({n}).",
        "cancelled": "Cancelled.",
        "cat_title": "📚 Choose a category to study.\nReminders use the same category.",
        "cat_all": "All words",
        "cat_greetings": "Greetings",
        "cat_polite": "Politeness",
        "cat_basic": "Basics",
        "cat_food": "Food",
        "cat_custom": "My words",
        "words_header": "📖 {cat} ({n}):",
        "words_empty": "No words in this category yet.",
        "ai_prompt": "🤖 Send a word or expression and I'll explain how it's really used.\nRequests left this week: {left}/{limit}\n/cancel to abort",
        "ai_wait": "⏳ Thinking…",
        "ai_limit": "🚫 AI request limit reached ({limit} per week).\nResets on: {when}.",
        "ai_footer": "AI requests left: {left}/{limit}",
        "ai_error": "😕 Could not get an answer from AI. Your request was not counted — try again later.",
        "int_title": "⏰ How often should I send words to review?\nCurrent: {current}",
        "i_60": "Every hour",
        "i_120": "Every 2 hours",
        "i_240": "Every 4 hours",
        "i_1440": "Once a day",
        "i_twice": "Morning and evening (9:00 / 20:00)",
        "i_off": "Turn off",
        "int_set": "✅ Notification interval: {label}",
        "notif_footer": "Tap the hidden text to reveal the translation",
        "hint": "Use the menu below 👇",
    },
}


def t(lang: str, key: str, **kw) -> str:
    return T.get(lang, T["en"])[key].format(**kw)


def cat_label(lang: str, cat: str | None) -> str:
    return t(lang, f"cat_{cat or 'all'}")
